Create SQL scripts for task
4eever/SQL-Test-Task pull request #1
Opened 2023-10-12 09:27 UTC by 4eever

2024-04-11 20:46 UTC, Leblyad requested changes
Следует доделать

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +	BankId INT,
У филиала должен быть банк/город (в данном случае поле может быть NULL)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +	StatusId INT,
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/f8f0bb0f-d1f1-4854-b733-627ee04f9e4b)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +	BankId INT,
Банковский аккаунт без клиента/банка? сомнительно
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/9fd94d4b-d423-4eb4-b663-6641a3c2797d)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +	AccountId INT,
Карточка без владельца

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +	CardBalance INT NOT NULL,
int для деняк не очень, советую подобрать другой тип.
без копеек спички будут стоить рубль 
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/85f1fdf8-a468-478e-8517-a3288c5bfc31)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--task 2
Красава 
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/803d544b-d498-44e7-83ae-52fa1766cabb)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--task3
Молодец 
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/43475151-0328-4041-bbd1-935963154cd1)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--INNER JOIN Cards c ON a.AccountId = c.AccountId
?

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--task4
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/0788715e-4d43-4442-8d12-165b9a698bc8)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--task5(GROUP BY)
обшибка 
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/d7ad2d79-5a5f-4494-bfaa-52709f2fb036)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--task5(���������)
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/d0a5c3a6-ab8c-4e4a-a563-a59681dff0c2)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +    -- �������� ������� ����������� �������
кодировке плохо

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--task6
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/7c06370e-5844-4425-8d23-e9e2ab65bcd3)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--task7
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/62feb0d1-b437-4de8-8bde-8860e5aa16bc)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--task7
перепроверь
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/23e5976a-7d74-4a7f-b37d-8b77a2a359d1)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +--task8
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/17f480c0-6b75-41f4-9052-011360cacf83)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +CREATE TRIGGER CheckAccountBalance
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/03d25b0d-7153-4404-a441-d2f880eb5cda)

2024-04-11 20:46 UTC, Leblyad commented on SQLQuery.sql
> +CREATE TRIGGER CheckCardBalance
Баланс карты не изменяется 
![image](https://github.com/4eever/SQL-Test-Task/assets/80668687/785e454e-e33c-4819-b055-f6ff00fd9fbd)

2024-04-18 23:10 UTC, 4eever commented on SQLQuery.sql
> +	BankId INT,
Понял, спасибо, исправил

2024-04-18 23:10 UTC, 4eever commented on SQLQuery.sql
> +	StatusId INT,
Спасибо, тоже исправил)

2024-04-18 23:11 UTC, 4eever commented on SQLQuery.sql
> +	BankId INT,
Тоже исправил)

2024-04-18 23:12 UTC, 4eever commented on SQLQuery.sql
> +	AccountId INT,
not null часто забывал поставить, но все исправил)

2024-04-18 23:17 UTC, 4eever commented on SQLQuery.sql
> +	CardBalance INT NOT NULL,
Спасибо, выбрал по итогу money, чтобы спички все-таки могли стоить 7 копеек :)
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/3d104419-e42b-4629-a05f-1a54acf0507e)

2024-04-18 23:22 UTC, 4eever commented on SQLQuery.sql
> +--task 2
Спасибо
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/43c5e32c-18ba-43f8-8038-0c8ac070959e)

2024-04-18 23:25 UTC, 4eever commented on SQLQuery.sql
> +--task3
Спасибо😊
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/9f6f7576-a53c-4d64-a0fa-6aa0b89e2a1a)

2024-04-18 23:28 UTC, 4eever commented on SQLQuery.sql
> +--INNER JOIN Cards c ON a.AccountId = c.AccountId
Тут я оставил в комменте, тк можно по сути что inner join использовать, что left join, но left по логике более предпочтительный, поэтому выбрал его. Эту строку вообще удалил :)

2024-04-18 23:29 UTC, 4eever commented on SQLQuery.sql
> +--task4
Спасибо)
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/e5776506-a49f-4736-8d4f-ee17bab793f7)

2024-04-18 23:31 UTC, 4eever commented on SQLQuery.sql
> +--task5(GROUP BY)
Да, достаточно глупая ошибка, но всё исправил)
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/05b2559c-ece3-4e60-b161-230f52b78674)

2024-04-18 23:33 UTC, 4eever commented on SQLQuery.sql
> +--task5(���������)
Спасибо)
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/cabd5ea5-2aea-451b-b148-9c2ccbc2ddeb)

2024-04-18 23:34 UTC, 4eever commented on SQLQuery.sql
> +    -- �������� ������� ����������� �������
Да, был момент, но больше его нет :)
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/896ee3b7-c8a8-4503-94af-4e59cc431282)

2024-04-18 23:35 UTC, 4eever commented on SQLQuery.sql
> +--task6
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/b67dc299-4d89-447c-b2b8-59cb7df961f5)

2024-04-18 23:37 UTC, 4eever commented on SQLQuery.sql
> +--task7
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/7993d691-9d1b-4b75-b096-a414f3d0a7cc)

2024-04-18 23:44 UTC, 4eever commented on SQLQuery.sql
> +--task7
Может я что-то пропустил, но я перепроверил и вроде бы все нормально
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/ef4f2e4f-d730-4a33-b140-5bdab3654d25)

2024-04-18 23:47 UTC, 4eever commented on SQLQuery.sql
> +--task8
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/102a81d7-b06d-441b-bc0a-131ac0f38261)

2024-04-18 23:48 UTC, 4eever commented on SQLQuery.sql
> +CREATE TRIGGER CheckAccountBalance
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/4ae74cba-6de8-4eb6-905d-dee90c4882b8)

2024-04-18 23:51 UTC, 4eever commented on SQLQuery.sql
> +CREATE TRIGGER CheckCardBalance
Может я что-то упускаю, но у меня все работает. Вот примеры успешного и неудачного обновлений
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/95b8fa69-8769-427e-a229-e6635d52211e)
![image](https://github.com/4eever/SQL-Test-Task/assets/109143314/28246a1b-bf9a-49fd-9589-ea17b15319f9)

2024-06-15 21:52 UTC, merged